source: website 
api: https://www.mapbox.com
url: https://www.mapbox.com
permalink: /:title
baseurl: /mapbox-studio
highlighter: true
mapboxjs: v2.0.0
tileapi: 'https://api.tiles.mapbox.com'
rdiscount:
  extensions: [smart]
defaults:
- scope:
    path: ""
    type: post
  values:
    layout: studiodoc
    date: 0000-01-01

### latest release
release: v0.0.3

