url: https://www.mapbox.com
api: https://www.mapbox.com/core
tileApi: https://api.tiles.mapbox.com
source: website
permalink: /:title/
baseurl: /mapbox-studio-classic
mapboxjs: v2.1.7
tileapi: 'https://api.tiles.mapbox.com'
defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: studiodoc

### latest release
release: v0.3.8
