environment:
  HOME: "c:\\projects\\tm2"
  AWS_ACCESS_KEY_ID:
    secure: "yr0cfv7H8uVu2iyIn93+brMT6oEhvm9FpkJPvwGZMlA="
  AWS_SECRET_ACCESS_KEY:
    secure: "cqTj03yqur/yCYCrMI0+A2ttBJ5r7uA8Xb0i0prEcM7lDLczYssPdp3DnqUnvIPN"
  matrix:
    - nodejs_version: 0.10

shallow_clone: true

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - node --version
  - echo %platform%
  - node -e "console.log(process.arch)"
  - node -e "console.log(process.env.HOME)"
  - ps: Start-FileDownload "https://mapnik.s3.amazonaws.com/dist/dev/VS-2014-runtime/vcredist_$env:Platform.exe"
  - .\vcredist_%platform%.exe /q /norestart
  - npm --version
  - npm install
  - npm test
  - node test/test-client.js

build: OFF
test: OFF
test_script: OFF
deploy: OFF
